#!/usr/bin/env bash
set -euo pipefail

: "${DEPLOYER_PRIVATE_KEY:?DEPLOYER_PRIVATE_KEY is required}"

MONAD_RPC_URL="${MONAD_RPC_URL:-https://testnet-rpc.monad.xyz}"
PERPLY_ARENA_ADDRESS="${PERPLY_ARENA_ADDRESS:-${VITE_PERPLY_ARENA_ADDRESS:-}}"
: "${PERPLY_ARENA_ADDRESS:?PERPLY_ARENA_ADDRESS (or VITE_PERPLY_ARENA_ADDRESS) is required}"

NEW_MIN_SETTLEMENT_INTERVAL="${NEW_MIN_SETTLEMENT_INTERVAL:-10}"
NEW_VOLATILITY_TRIGGER_BPS="${NEW_VOLATILITY_TRIGGER_BPS:-15}"
NEW_SETTLEMENT_STRENGTH_BPS="${NEW_SETTLEMENT_STRENGTH_BPS:-8000}"
NEW_MAX_SETTLEMENT_TRANSFER_BPS="${NEW_MAX_SETTLEMENT_TRANSFER_BPS:-3000}"
NEW_OPEN_FEE_BPS="${NEW_OPEN_FEE_BPS:-50}"
NEW_CLOSE_FEE_BPS="${NEW_CLOSE_FEE_BPS:-50}"
NEW_SETTLEMENT_FEE_BPS="${NEW_SETTLEMENT_FEE_BPS:-1}"
NEW_CONGESTION_START_BPS="${NEW_CONGESTION_START_BPS:-1000}"
NEW_CONGESTION_FULL_BPS="${NEW_CONGESTION_FULL_BPS:-5000}"
NEW_MAX_CONGESTION_FEE_BPS="${NEW_MAX_CONGESTION_FEE_BPS:-50}"
NEW_MAINTENANCE_BASE_BPS="${NEW_MAINTENANCE_BASE_BPS:-600}"
NEW_MAINTENANCE_LEVERAGE_BPS="${NEW_MAINTENANCE_LEVERAGE_BPS:-40}"
NEW_LIQUIDATION_PENALTY_BPS="${NEW_LIQUIDATION_PENALTY_BPS:-200}"
NEW_LIQUIDATOR_REWARD_SHARE_BPS="${NEW_LIQUIDATOR_REWARD_SHARE_BPS:-5000}"

echo "Sending setRiskParams tx on Monad Testnet..."
echo "Arena: ${PERPLY_ARENA_ADDRESS}"
echo "RPC: ${MONAD_RPC_URL}"
echo "Fees (bps): open=${NEW_OPEN_FEE_BPS}, close=${NEW_CLOSE_FEE_BPS}, settlement=${NEW_SETTLEMENT_FEE_BPS}"

cast send "${PERPLY_ARENA_ADDRESS}" \
  "setRiskParams(uint32,uint16,uint16,uint16,uint16,uint16,uint16,uint16,uint16,uint16,uint16,uint16,uint16,uint16)" \
  "${NEW_MIN_SETTLEMENT_INTERVAL}" \
  "${NEW_VOLATILITY_TRIGGER_BPS}" \
  "${NEW_SETTLEMENT_STRENGTH_BPS}" \
  "${NEW_MAX_SETTLEMENT_TRANSFER_BPS}" \
  "${NEW_OPEN_FEE_BPS}" \
  "${NEW_CLOSE_FEE_BPS}" \
  "${NEW_SETTLEMENT_FEE_BPS}" \
  "${NEW_CONGESTION_START_BPS}" \
  "${NEW_CONGESTION_FULL_BPS}" \
  "${NEW_MAX_CONGESTION_FEE_BPS}" \
  "${NEW_MAINTENANCE_BASE_BPS}" \
  "${NEW_MAINTENANCE_LEVERAGE_BPS}" \
  "${NEW_LIQUIDATION_PENALTY_BPS}" \
  "${NEW_LIQUIDATOR_REWARD_SHARE_BPS}" \
  --rpc-url "${MONAD_RPC_URL}" \
  --private-key "${DEPLOYER_PRIVATE_KEY}"

echo "Done."
